apiVersion: v1
kind: Service
metadata:
  name: openpitrix-etcd
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
spec:
  selector:
    app: openpitrix
    tier: etcd
  clusterIP: None
  ports:
  - name: tcp
    protocol: TCP
    port: 2379
    targetPort: 2379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openpitrix-etcd-pvc
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-etcd-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: etcd
spec:
  selector:
    matchLabels:
      app: openpitrix
      tier: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openpitrix
        tier: etcd
    spec:
      containers:
      - name: openpitrix-etcd
        image: appcelerator/etcd:3.3.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
          name: etcd
        volumeMounts:
        - name: etcd-persistent-storage
          mountPath: /data
      volumes:
      - name: etcd-persistent-storage
        persistentVolumeClaim:
          claimName: openpitrix-etcd-pvc
