apiVersion: v1
kind: Service
metadata:
  name: openpitrix-job-manager
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-job-manager
spec:
  selector:
    app: openpitrix
    component: openpitrix-job-manager
  ports:
  - name:  openpitrix-job-manager
    protocol: TCP
    port: 9106
    targetPort: 9106
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-job-manager-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-job-manager
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-job-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-job-manager
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc.cluster.local 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc.cluster.local 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-job-manager
        image: ${IMAGE}
        imagePullPolicy: Always
        command:
          - job-manager
        ports:
        - containerPort: 9106
          name: job-manager
        env:
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "job"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi

